Добавлены плагины для трекинга доп событий в Google Analytics.
freelancehunt/Casper pull request #3
Opened 2019-06-18 13:04 UTC by pridumkuvatyj

https://my.teamline.app/tasks/WyAJb3jmRP7Y23mEA

2019-06-18 13:06 UTC, pridumkuvatyj commented
Плагины подключил только на страницах постов.

2019-06-18 13:11 UTC, pridumkuvatyj commented on default.hbs
> +            let middlePostElementIndex = Math.floor($('.post-content > *').length / 2);
Примерно средний элемент в посте.

2019-06-18 13:11 UTC, pridumkuvatyj commented on default.hbs
> +    {{#is "post"}}
Трекать только на странице поста.

2019-06-19 12:36 UTC, thedotedge requested changes
Полагаю, что в теме этому не место. Скрипты можно грузить с CDN, далее инитить в https://freelancehunt.com/blog/ghost/#/settings/code-injection

2019-06-19 12:39 UTC, pridumkuvatyj commented
> Полагаю, что в теме этому не место. Скрипты можно грузить с CDN, далее инитить в https://freelancehunt.com/blog/ghost/#/settings/code-injection

Я тоже так думал, но условие `{{#is "post"}}{{/is}}` в Code injection не работает и это будет отрабатывать на всех страницах.

2019-06-19 13:21 UTC, thedotedge commented
Ничего страшного + можно инициализировать по наличию элемента в DOM?

2019-06-19 13:21 UTC, pridumkuvatyj commented
Ок, сейчас поправлю.

2019-06-19 14:07 UTC, pridumkuvatyj commented
@thedotedge, screentime плагина нет на cdn, альтернативы не нагуглил.
Есть https://www.pressboardmedia.com/comparing-google-analytics-time-on-page-to-pressboards-active-reading-time/, который может заменить оба скрипта. Но, думаю, у них сервис платный.

2019-06-19 16:02 UTC, thedotedge commented
https://cdn.jsdelivr.net/npm/screentime@1.0.0/screentime.js?

2019-06-20 10:21 UTC, pridumkuvatyj commented
Забыл за него, на cdnjs смотрел :man_facepalming:
Вылил скрипт в нижний блок code injection, PR закрываю.

2019-06-20 10:21 UTC, closed without merging